Repository Netcracker/qubership-dbaas, pull requests merged in 2025-07, with the labels that each got.

#75 fix: filter all databases with null physical id
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/service/DebugService.java
  dbaas/dbaas-aggregator/src/test/java/org/qubership/cloud/dbaas/service/DebugServiceTest.java
Labels: bug

#85 build: disable Sonar checks during commits
  .github/workflows/maven-build.yaml
Labels: build

#83 docs: update README.md
  README.md
Labels: documentation

#82 refactor: small cosmetic fixes
  dbaas/dbaas-aggregator/src/main/java/db/migration/postgresql/V1_008__TransformClassifier.java
  dbaas/dbaas-aggregator/src/main/java/db/migration/postgresql/V1_013__RepairConnectionProperties.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/controller/abstact/AbstractDatabaseAdministrationController.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/controller/v3/AggregatedBackupAdministrationControllerV3.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/controller/v3/AggregatedBackupRestoreControllerV3.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/dao/jpa/DatabaseDbaasRepositoryImpl.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/dao/jpa/DatabaseRegistryDbaasRepositoryImpl.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/entity/pg/BgDomain.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/entity/pg/Database.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/entity/shared/AbstractDatabaseRegistry.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/monitoring/annotation/TimeMeasure.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/repositories/pg/jpa/BgDomainRepository.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/service/AbstractDbaasAdapterRESTClient.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/service/AggregatedDatabaseAdministrationService.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/service/BalancingRulesService.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/service/BlueGreenService.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/service/CryptoServicePasswordEncryption.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/service/DBBackupsService.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/service/DBaaService.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/service/DebugService.java
  dbaas/dbaas-aggregator/src/main/java/org/qubership/cloud/dbaas/service/MigrationService.java
  dbaas/dbaas-aggregator/src/test/java/org/qubership/cloud/dbaas/dao/h2/H2DatabaseRepositoriesTest.java
  dbaas/dbaas-aggregator/src/test/java/org/qubership/cloud/dbaas/dao/jpa/DatabaseRegistryRepositoryTest.java
  dbaas/dbaas-aggregator/src/test/java/org/qubership/cloud/dbaas/integration/config/PostgresqlContainerResource.java
  dbaas/dbaas-aggregator/src/test/java/org/qubership/cloud/dbaas/integration/stability/BlueGreenStabilityTest.java
  dbaas/dbaas-aggregator/src/test/java/org/qubership/cloud/dbaas/service/DBaaServiceTest.java
  dbaas/dbaas-aggregator/src/test/java/org/qubership/cloud/dbaas/service/InstructionServiceTest.java
  dbaas/dbaas-aggregator/src/test/java/org/qubership/cloud/dbaas/service/MonitoringServiceTest.java
  dbaas/dbaas-aggregator/src/test/java/org/qubership/cloud/dbaas/service/UserServiceTest.java
  dbaas/encryption-services-cipher/src/main/java/org/qubership/cloud/encryption/cipher/EncryptionRequest.java
  dbaas/encryption-services-cipher/src/main/java/org/qubership/cloud/encryption/cipher/build/EncryptionRequestBuilder.java
  dbaas/encryption-services-cipher/src/main/java/org/qubership/cloud/encryption/cipher/provider/V2CryptoProvider.java
  dbaas/encryption-services-cipher/src/main/java/org/qubership/cloud/encryption/config/keystore/type/EnvironmentKeystoreConfigBuilder.java
  dbaas/encryption-services-cipher/src/main/java/org/qubership/cloud/encryption/config/keystore/type/KeyConfig.java
  dbaas/encryption-services-cipher/src/main/java/org/qubership/cloud/encryption/config/keystore/type/MutableKeyConfig.java
  dbaas/encryption-services-cipher/src/main/java/org/qubership/cloud/encryption/config/xml/ConfigurationCryptoProvider.java
  dbaas/encryption-services-cipher/src/main/java/org/qubership/cloud/encryption/config/xml/DefaultConfigurationCryptoProvider.java
  dbaas/encryption-services-cipher/src/main/java/org/qubership/cloud/encryption/key/EnvironmentKeyStore.java
  dbaas/encryption-services-cipher/src/main/java/org/qubership/cloud/encryption/key/LocalKeyStore.java
  dbaas/encryption-services-cipher/src/test/java/org/qubership/cloud/encryption/CryptoServiceStub.java
  dbaas/encryption-services-cipher/src/test/java/org/qubership/cloud/encryption/key/LocalKeyStoreTest.java
Labels: bug
